name: 'lgtm reviewer'
description: 'Lonely Gaddem Timeless Manager'
inputs:
  who-to-greet: # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  GITHUB_TOKEN:
    description: 'Github token of the repository (automatically created by Github)'
    required: true
  GIT_DIFF_FILTERED:
    description: 'diff file'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
