on:
  pull_request:
    types:
      - synchronize

jobs:
  lgtm-reviewer:
    runs-on: ubuntu-latest
    name: LGTM Reviewer
    steps:
      - name: lgtm-reviewer
        uses: aiandrox/lgtm-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
